version: '3.8'

services:
  cloudapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sortyx-cloudapp
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DEBUG=True
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
      - ./models:/app/models
      - ./static:/app/static
      - ./templates:/app/templates
      - ./uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
