services:
  - type: web
    name: sortyx-backend
    runtime: python
    plan: free
    # CRITICAL: Specify Python version here
    runtimeVersion: "3.12.7"
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: PORT
        value: 8000
      - key: ENVIRONMENT
        value: production
    autoDeploy: true
