services:
  - type: web
    name: sortyx-backend
    runtime: python
    plan: free
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.4
      - key: GEMINI_API_KEY
        sync: false
      - key: PORT
        value: 8000
      - key: ENVIRONMENT
        value: production
    # Force Python 3.12.4
    autoDeploy: true
